ARG metis_env="production"
ARG client_url="http://160.251.137.133"
ARG server_url="http://160.251.204.153"
# build
FROM node:18.22.4 as builder
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json", "./"]
RUN mkdir -p /root/.cache
RUN npm install --non-interactive --frozen-lockfile
COPY . .
ARG metis_env
ENV NODE_ENV="production"
ENV METIS_ENV=${metis_env}
ENV URL=${client_url}
ENV CLIENT_SIDE_GRAPHQL="${server_url}/graphql"
ENV SERVER_SIDE_GRAPHQL="${server_url}/graphql"
RUN npm run build

# install packages
FROM node:18.22.4 as node_modules
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json", "./"]
RUN mkdir -p /root/.cache
RUN npm install --non-interactive --frozen-lockfile --prod

# run
FROM node:18.22.4
WORKDIR /usr/src/app
ENV NODE_ENV="production"
ENV METIS_ENV=${metis_env}
ENV URL=${client_url}
COPY --from=builder /usr/src/app/public /usr/src/app/public
COPY --from=builder /usr/src/app/.next /usr/src/app/.next
COPY --from=builder /usr/src/app/next.config.js /usr/src/app/next.config.js
COPY --from=node_modules /usr/src/app/node_modules /usr/src/app/node_modules
EXPOSE 3000
CMD ["./node_modules/.bin/next", "start", "-p", "3000"]