import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { ApolloClient, InMemoryCache, gql } from '@apollo/client'
const inter = Inter({ subsets: ['latin'] })

const client = new ApolloClient({
  uri: 'http://localhost:3000/api/graphql',
  cache: new InMemoryCache(),
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Top Page</p>
      </main>
    </>
  )
}
