name: 'todoapp-client deploy'
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKER_USER_NAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USER_NAME}}/todoapp-client:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          port: ${{secrets.SSH_PORT}}
          script: |
            mkdir -p ~/.ssh
            echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/deploy_key
            chmod 600 ~/.ssh/deploy_key
            docker build -t todoapp-client .
            docker save todoapp-client | gzip | ssh -i ~/.ssh/deploy_key ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}} 'gunzip | docker load'
            ssh-keyscan ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts
            ssh -T -i ~/.ssh/deploy_key ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}} 'docker rm -f todoapp-client || true && docker run -d --name=todoapp-client -p $port:80 todoapp-client'