name: 'todoapp-client deploy'
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with: 
          node-version: '18'
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run:  yarn install
      
      - name: Deploy Conoha VPS
        env:
          CONOHA_VPS_SSH_KEY: ${{ secrets.SK }}
          CONOHA_VPS_USER: ${{ secrets.SSH_USERNAME }}
          CONOHA_VPS_HOST: ${{ secrets.SSH_HOST }}
          CONOHA_VPS_DIR: ${{ secrets.SSH_DIR }}
          run: sh .github/workflows/deploy.sh
