name: 'todoapp-client deploy'
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKER_USER_NAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USER_NAME}}/todoapp-client:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy Conoha VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_DIR: ${{ secrets.SSH_DIR }}
        run: |
          ssh -o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -i ssh_key user@bastion" \
            ${SSH_USERNAME}@${SSH_HOST} "chmod +x deploy.sh && ./deploy.sh"