name: 'todoapp-client deploy'
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKER_USER_NAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USER_NAME}}/todoapp-client:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deploy Conoha VPS
        uses: appleboy/ssh-action@master
        with:
          CONOHA_VPS_SSH_KEY: ${{ secrets.SSH_SECRET_KEY }}
          CONOHA_VPS_SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          CONOHA_VPS_USER: ${{ secrets.SSH_USERNAME }}
          CONOHA_VPS_HOST: ${{ secrets.SSH_HOST }}
          CONOHA_VPS_DIR: ${{ secrets.SSH_DIR }}
      - name: Run Shell Script
        run: sh .github/workflows/deploy.sh